--01 �룊洹� �뿰遊됰낫�떎 �쟻�� �썡湲됱쓣 諛쏅뒗 吏곸썝�� 紐� 紐�?
SELECT count(*) 
FROM EMPLOYEES e
WHERE SALARY < (
	SELECT AVG(SALARY)
	FROM EMPLOYEES A
	);
	
--02 각 부서 최고 급여 받는 사원 조회
SELECT EMPLOYEE_ID, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE (DEPARTMENT_ID, SALARY) IN (
	SELECT DEPARTMENT_ID, MAX(SALARY)
	FROM EMPLOYEES
	GROUP BY DEPARTMENT_ID
	)
ORDER BY SALARY DESC;

SELECT DEPARTMENT_ID, MAX(SALARY)
	FROM EMPLOYEES
	GROUP BY DEPARTMENT_ID;